# Generated by Django 5.0.4 on 2024-04-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imageUrl',
            field=models.CharField(default='Ass', max_length=500),
            preserve_default=False,
        ),
    ]
