# Generated by Django 5.0.4 on 2024-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
