# Generated by Django 5.0.4 on 2024-04-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
